**Ejercicio 1** Write a Python program to display the first and last colors from the following list. 
color_list = ["Red","Green","White" ,"Black"]

In [1]:
color_list= ["Red", "Green", "White", "Black"]

color_list[::3]

['Red', 'Black']

**Ejercicio 2**  Write a Python function that takes a sequence of numbers and determines if all the numbers are different from each other. 

In [2]:
print("Dame 2 números")

a= input('El primer numero es:')
b= input('El segundo numero es:')

a==b

Dame 2 números
El primer numero es:34
El segundo numero es:34


True

**Exercise 3** Write a function that tells if a given number n is even, if not, then returns twice the number.

Write the description of the function in more than one line. Make additional comments in one line

Afterwards, call the function with different inputs, use the ? notation.

In [16]:
#definimos la funcion 
n= int(input("dame un numero:"))

def f(n):
    '''
    Esta funcion toma un numero y verifica si este es par o impar 
    como argumento se tiene un numero dado por el usuario.
    '''
    if n%2!=0:
        print(n,"es tu numero y es impar", "y este es el doble de tu numero:", n*2) #hacemos uso de condicionales y ayudandonos de la operacion modulo que consiste en obtener el residuo de un cociente
    else:
        print(n, "es tu numero y es par")
        
f(n)

dame un numero:68
68 es tu numero y es par


In [17]:
f?


**Exercise 4** 

Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [21]:
import numpy as np

In [23]:
intervalo= np.linspace(-1.3, 2.5, 64)

intervalo

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

**Exercise 5** 

Generate an array of length 3n filled with the cyclic pattern 1, 2, 3.

usando linspace o arange

usando tile


In [4]:
import numpy as np

In [27]:
A=np.array([1,2,3])

np.tile(A,(1,5))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

**Exercise 6**

Create an array of the first 10 odd integers.

usando linspace

usando formfunction

In [11]:
import numpy as np

In [12]:
x= np.linspace(1, 21, 3)

x

array([ 1., 11., 21.])

In [37]:
f=np.fromfunction(lambda i, j: (2*j)-1, (1,11))

f

array([[-1.,  1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.]])

**Exercise 7**

Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

usar vistas 

In [6]:
import numpy as np

In [41]:
f=np.fromfunction(lambda i, j: i, (1,10))

f


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Exercise 8**

Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a 

slicing+striding approach.

usar una mascara

In [42]:
import numpy as np

In [69]:
A= np.zeros((1,8))
B= np.ones((1,4))


print(A,'\n',B)

[[0. 0. 0. 0. 0. 0. 0. 0.]] 
 [[1. 1. 1. 1.]]


In [58]:
C=np.resize(A,(3,3))

C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
mascara= A==1

mascara

array([[False, False, False, False, False, False, False, False]])

In [67]:
A>0

array([[False, False, False, False, False, False, False, False]])

In [68]:
A[A>0]=1
A

array([[0., 0., 0., 0., 0., 0., 0., 0.]])